site_name: dakku documentation
site_url: https://xehoth.github.io/dakku/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 

nav:
  - Home: /
  - Classes: Classes/
  - Namespaces: Namespaces/
  - Modules: Modules/
  - Files: Files/
  - Related Pages: Pages/
  - Examples: Examples/

