site_name: dakku documentation
site_url: https://xehoth.github.io/dakku/
repo_url: https://github.com/xehoth/dakku/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: /dakku/
  - Classes: /dakku/Classes/
  - Namespaces: /dakku/Namespaces/
  - Modules: /dakku/Modules/
  - Files: /dakku/Files/
  - Related Pages: /dakku/Pages/
  - Examples: /dakku/Examples/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js