add_requires("spdlog >=1.9.2", {configs = {fmt_external = false}})
add_requires("nlohmann_json >=3.10.5")

target("dakku.core")
  set_kind("shared")
  add_defines("DAKKU_BUILD_MODULE=DAKKU_CORE_MODULE")
  add_includedirs(os.projectdir() .. "/src", {public = true})
  add_files("*.cpp")
  add_packages("spdlog", "nlohmann_json", {public = true})
  add_deps("dakku.imageio")