name: build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Clang
        if: matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Get XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: XMake Config for Clang
        if: matrix.os == 'ubuntu-latest'
        run: 'xmake f --toolchain=clang -c -y'
      - name: Build Test
        run: 'xmake f --build_test=y -y'
      - name: Build
        run: xmake build -y
      - name: Run Test
        run: xmake run test
