name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      XMAKE_PKG_CACHEDIR: "/home/runner/work/xmake/xmake-cache"
      XMAKE_PKG_INSTALLDIR: "/home/runner/work/xmake/xmake-packages"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.4'
      - name: Get XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Cache XMake
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.XMAKE_PKG_CACHEDIR }}
            ${{ env.XMAKE_PKG_INSTALLDIR }}
          key: ${{ matrix.os }}-${{ hashFiles('xmake-requires.lock') }}
          restore-keys: ${{ matrix.os }}-
      - name: XMake Config for Clang & Test
        run: 'xmake f --build_test=y -c -y'
      - name: Build
        run: xmake build -w -y -vD
