name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Get XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Set xmake package cache path
        run: echo "XMAKE_PKG_CACHEDIR=`pwd`/xmake-cache" >> $GITHUB_ENV
      - name: Cache XMake
        uses: actions/cache@v3
        with:
          path: xmake-cache
          key: ${{ matrix.os }}-${{ matrix.arch }}
      - name: XMake Config for Clang & Test
        run: 'xmake f --toolchain=clang --build_test=y -c -y -vD'
      - name: Build
        run: xmake build -w -y -vD
      - name: Run Test
        run: xmake run test
