name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - name: Get XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Set xmake package cache path
        run: |
          echo "XMAKE_PKG_CACHEDIR=${{ runner.workspace }}/../xmake-cache" >> $GITHUB_ENV
          echo "XMAKE_PKG_INSTALLDIR=${{ runner.workspace }}/../xmake-packages" >> $GITHUB_ENV
      - name: Cache XMake
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.workspace }}/../xmake-cache
            ${{ runner.workspace }}/../xmake-packages
          key: ${{ matrix.os }}-${{ hashFiles('xmake-requires.lock') }}
      - name: XMake Config for Clang & Test
        run: 'xmake f --build_test=y -c -y'
      - name: Build
        run: xmake build -w -y -vD
