name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      XMAKE_PKG_CACHEDIR: "D:/a/xmake/xmake-cache"
      XMAKE_PKG_INSTALLDIR: "D:/a/xmake/xmake-packages"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Cache XMake
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.XMAKE_PKG_CACHEDIR }}
            ${{ env.XMAKE_PKG_INSTALLDIR }}
          key: ${{ matrix.os }}-${{ hashFiles('xmake-requires.lock') }}
          restore-keys: ${{ matrix.os }}-
      - name: Config Test
        run: 'xmake f --build_test=y -c -y'
      - name: Build
        run: xmake build -w -y -vD
      - name: Run Test
        run: xmake run test
