add_requires("openimageio >=2.3.13")
target("dakku.imageio")
  set_languages("c++17")
  set_kind("shared")
  add_defines("DAKKU_BUILD_MODULE=DAKKU_IMAGEIO_MODULE")
  add_includedirs(os.projectdir() .. "/src", {public = true})
  add_packages("openimageio")
  add_files("*.cpp")